language: python
python:
- '2.7'
sudo: required
install:
- pip install setuptools wheel
script:
- python setup.py sdist bdist_wheel
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file: dist/*
  skip_cleanup: true
  on:
    tags: true
env:
  global:
    secure: sOQ51GeHG3tZC8EnJvie/XyTK/+QqmrhE22gBUaFZ+GwTWgT/Xi8PLguwl1kfX5ZFIsYrbSW8LVhk0IHuWX7mvPT+eBncpcmSZ3H5ml/UUAPqxVoLEoBkFqoGuIOGYMvdsIiAWgEdQ9A0qXZtDsOi5d3sCo5nporhE63ezm9JjRO1VqDmNxCGpZ+9EuhWs2hDFfaJptviNuEAxKeiWhdayTw9aeh5EiDxk65wc2mwmRvLELv8GI1aklKiNcDks3L7HCmhh9CZ+/W0d7Zobz67wolt2IKhc+UDhjbeW8c2IcWj8Hy/rSwophtYuNLRc3lx7vNaOVgUhAZpS1lF5eiJDCrfHfBM5FLqzSDKCqn5TeXuLbzXOOkCIsw9GvZJCbrgVEpjL9jCOPvuz2Ik9v1r7Txlt3E9lLizyYMD7hrdFSIdz9VrOfRqeKu5+U6JnCobchRxrE9bMHQsQmddjyndQaKckweHIHYpTgGfqtU0kPt0JRNh6/bFy8YHOe8IdQx9zucCOQFuK5k/QxLOmzF9hoLaE/HzPcYd22ycU9aZK9tXyiSg/6qhAQyMoGgKUEJ8Y1xcnBVFeayIB0Wd2nigqdxl/zbNMJHXse58e0zHJI6Dd8fJRYwJ6bEFqsSa55EQqDWLcz7EbteNX2FhH9MnYOQdpcPSZWuLERJAEpZgl0=
