language: python
python:
  - "2.7"
sudo: required
install:
- pip install setuptools wheel
script:
- python setup.py sdist bdist_wheel
deploy:
  provider: releases
  api_key:
    secure: XtPXmMfl0xaedXcUqHLdl9qBxAY5YH6pMvAvt2cRLYd/rBsV2gTpIrIPRI6tnbh6WSB4KlwnI8F9Q+w4Y9WEnuEVmYeDkJCJplg9P1m5nsTgT0RoIlHfERrOyqLh0YIC6reRiAFRcusMXcMa7ONVMgFrG/i4DGlbGOmsGAn/5NRp2LU7HS96ITwsdmmJQS4HIFj6wJvngHMdIYUJxl2qaYqNKjuyZgZND1aKwYbm1w1NetNFA1IL40j59+N/SL0qbVvB/eNzFuKwKd5cIOXqO8T/LeZkcuWdpj8wnbL9wnWfbchyOSt8R0Lw4LjbtKzGsydMNtJG/ySbdvrbs9CIdYPNsVQ+cJjAyNQJfnUZCE9CzzCB280/UhVIrOmyruZaecTosmFmImNwaqRw+anNOO0lU+/HSM+JV7glUQB+9wG5FhmvWx98MYlNXb0T2tdvHPa9t7NNpYYyNIF206cCTX00W66cpLbQU+Smu5I1fmsZdpy6kcH26nuumXyd7j0IZXy4AcG27QwReRIBmyg+TfPLkCj+bhCxTUEb9GYGVIvXMnvu35BgDnDS6P5aWEiHvUln3zvopv7gtoq+dnkAioQ3t3Uo6XL2vxodOUcP7mLcY1pE2kDussI6TqgwnqlPgb65Vtig8VWUu3r7p0+FI3lSRUdlPf3DqDqfDSy0y9Y=
  file: dist/*
  skip_cleanup: true
  on:
    tags: true
